#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# report.sh -- Markdown report generation for E2E tests
# ============================================================================

generate_report() {
    local output_file="$1"

    {
        echo "# E2E Pipeline Counter Verification Report"
        echo ""
        echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        echo ""

        # Summary
        echo "## Summary"
        echo ""
        echo "| Metric | Count |"
        echo "|--------|-------|"
        echo "| Total  | $((PASS_COUNT + FAIL_COUNT)) |"
        echo "| Pass   | ${PASS_COUNT} |"
        echo "| Fail   | ${FAIL_COUNT} |"
        echo ""

        # Results table
        echo "## Results"
        echo ""
        echo "| # | Scenario | Result |"
        echo "|---|----------|--------|"
        local idx=1
        for result in "${SCENARIO_RESULTS[@]:-}"; do
            if [ -z "$result" ]; then
                continue
            fi
            local status="${result%%|*}"
            local name="${result#*|}"
            echo "| ${idx} | ${name} | ${status} |"
            idx=$((idx + 1))
        done
        echo ""

        # Evidence
        echo "## Evidence"
        echo ""
        for entry in "${SCENARIO_EVIDENCE[@]:-}"; do
            if [ -z "$entry" ]; then
                continue
            fi
            local name="${entry%%|*}"
            local evidence="${entry#*|}"
            echo "### ${name}"
            echo ""
            echo '```'
            echo "${evidence}"
            echo '```'
            echo ""
        done

        echo "---"
        echo ""
        echo "*Generated by tests/e2e/run-all.sh*"
    } > "$output_file"
}
