#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# report.sh -- Categorized Markdown report generation for E2E tests
# ============================================================================

# Category definitions: name, start_index (0-based), end_index (inclusive)
_REPORT_CATEGORIES=(
    "Pipeline Counters|0|9"
    "Business Metrics|10|22"
    "OID Mutations|23|25"
    "Device Lifecycle|26|28"
    "Watcher Resilience|29|32"
)

generate_report() {
    local output_file="$1"
    local total=${#SCENARIO_RESULTS[@]:-0}

    {
        echo "# E2E System Verification Report"
        echo ""
        echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        echo ""

        # Summary table
        echo "## Summary"
        echo ""
        echo "| Metric | Count |"
        echo "|--------|-------|"
        echo "| Total  | $((PASS_COUNT + FAIL_COUNT)) |"
        echo "| Pass   | ${PASS_COUNT} |"
        echo "| Fail   | ${FAIL_COUNT} |"
        echo ""

        # Categorized results
        for category in "${_REPORT_CATEGORIES[@]}"; do
            local cat_name="${category%%|*}"
            local rest="${category#*|}"
            local start_idx="${rest%%|*}"
            local end_idx="${rest#*|}"

            # Skip category if no scenarios ran in this range
            if [ "$start_idx" -ge "$total" ]; then
                continue
            fi

            # Clamp end index to actual results
            local effective_end="$end_idx"
            if [ "$effective_end" -ge "$total" ]; then
                effective_end=$((total - 1))
            fi

            echo "## ${cat_name} (Scenarios $(printf '%02d' $((start_idx + 1)))-$(printf '%02d' $((effective_end + 1))))"
            echo ""
            echo "| # | Scenario | Result |"
            echo "|---|----------|--------|"

            for idx in $(seq "$start_idx" "$effective_end"); do
                local result="${SCENARIO_RESULTS[$idx]:-}"
                if [ -z "$result" ]; then
                    continue
                fi
                local status="${result%%|*}"
                local name="${result#*|}"
                local num=$((idx + 1))
                echo "| ${num} | ${name} | ${status} |"
            done
            echo ""
        done

        # Evidence section (flat)
        echo "## Evidence"
        echo ""
        for entry in "${SCENARIO_EVIDENCE[@]:-}"; do
            if [ -z "$entry" ]; then
                continue
            fi
            local name="${entry%%|*}"
            local evidence="${entry#*|}"
            echo "### ${name}"
            echo ""
            echo '```'
            echo "${evidence}"
            echo '```'
            echo ""
        done

        echo "---"
        echo ""
        echo "*Generated by tests/e2e/run-all.sh*"
    } > "$output_file"
}
