apiVersion: v1
kind: ConfigMap
metadata:
  name: simetra-config
  namespace: simetra
data:
  appsettings.k8s.json: |
    {
      "Site": {
        "Name": "site-lab-01"
      },
      "Otlp": {
        "Endpoint": "http://otel-collector:4317",
        "ServiceName": "simetra-supervisor"
      },
      "SnmpListener": {
        "Port": 10162
      },
      "HeartbeatJob": {
        "IntervalSeconds": 15
      },
      "Liveness": {
        "GraceMultiplier": 2.0
      },
      "Devices": [],
      "OidMap": {},
      "Logging": {
        "LogLevel": {
          "Default": "Debug"
        },
        "EnableConsole": true
      }
    }
  oidmap-obp.json: |
    {
      "OidMap": {
        "1.3.6.1.4.1.47477.10.21.1.3.1.0": "obp_link_state_L1",
        "1.3.6.1.4.1.47477.10.21.1.3.4.0": "obp_channel_L1",
        "1.3.6.1.4.1.47477.10.21.1.3.10.0": "obp_r1_power_L1",
        "1.3.6.1.4.1.47477.10.21.1.3.11.0": "obp_r2_power_L1",
        "1.3.6.1.4.1.47477.10.21.1.3.12.0": "obp_r3_power_L1",
        "1.3.6.1.4.1.47477.10.21.1.3.13.0": "obp_r4_power_L1",
        "1.3.6.1.4.1.47477.10.21.2.3.1.0": "obp_link_state_L2",
        "1.3.6.1.4.1.47477.10.21.2.3.4.0": "obp_channel_L2",
        "1.3.6.1.4.1.47477.10.21.2.3.10.0": "obp_r1_power_L2",
        "1.3.6.1.4.1.47477.10.21.2.3.11.0": "obp_r2_power_L2",
        "1.3.6.1.4.1.47477.10.21.2.3.12.0": "obp_r3_power_L2",
        "1.3.6.1.4.1.47477.10.21.2.3.13.0": "obp_r4_power_L2",
        "1.3.6.1.4.1.47477.10.21.3.3.1.0": "obp_link_state_L3",
        "1.3.6.1.4.1.47477.10.21.3.3.4.0": "obp_channel_L3",
        "1.3.6.1.4.1.47477.10.21.3.3.10.0": "obp_r1_power_L3",
        "1.3.6.1.4.1.47477.10.21.3.3.11.0": "obp_r2_power_L3",
        "1.3.6.1.4.1.47477.10.21.3.3.12.0": "obp_r3_power_L3",
        "1.3.6.1.4.1.47477.10.21.3.3.13.0": "obp_r4_power_L3",
        "1.3.6.1.4.1.47477.10.21.4.3.1.0": "obp_link_state_L4",
        "1.3.6.1.4.1.47477.10.21.4.3.4.0": "obp_channel_L4",
        "1.3.6.1.4.1.47477.10.21.4.3.10.0": "obp_r1_power_L4",
        "1.3.6.1.4.1.47477.10.21.4.3.11.0": "obp_r2_power_L4",
        "1.3.6.1.4.1.47477.10.21.4.3.12.0": "obp_r3_power_L4",
        "1.3.6.1.4.1.47477.10.21.4.3.13.0": "obp_r4_power_L4"
      }
    }
