apiVersion: v1
kind: Service
metadata:
  name: snmp-collector
  namespace: simetra
  labels:
    app: snmp-collector
spec:
  type: ClusterIP
  selector:
    app: snmp-collector
  ports:
  - name: health
    port: 8080
    protocol: TCP
    targetPort: health
  - name: snmp
    port: 162
    protocol: UDP
    targetPort: snmp
